var express = require("express");
var app = express();
var router = express.Router();
var path = require("path");
const { refreshCookies } = require('../bin/auth')

const approve = require('./approve')
const approvescantime = require('./approvescantime')
const authorize = require('./authorize')
const calendar = require('./calendar')
const contact = require('./contact')
const cross = require('./cross')
const delreq = require('./delreq')
const departmentleaveview = require('./departmentleaveview')
const easypass = require('./easypass')
const editentitle = require('./editentitle')
const excelexport = require('./excelexport')
const exportmanager = require('./exportmanager')
const forms = require('./forms')
const getip = require('./getip')
const getlar = require('./getlar')
const handbook = require('./handbook')
const hr = require('./hr')
const hrexport = require('./hrexport')
const index = require('./index')
const lar = require('./lar')
const leavelist = require('./leavelist')
const leavereport = require('./leavereport')
const listtable = require('./listtable')
const login = require('./login')
const memo = require('./memo')
const managerleavelist = require('./managerleavelist')
const manualattendance = require('./manualattendance')
const privacy = require('./privacy')
const proc = require('./proc')
const profile = require('./profile')
const refreshdata = require('./refreshdata')
const reserve = require('./reserve')
const reservelist = require('./reservelist')
const reporttime = require('./reporttime')
const saleactive = require('./saleactive')
const setting = require('./setting2')
const search = require('./search')
const searchb = require('./searchb')
const sumlar = require('./sumlar')
const vacationa = require('./vacationa')

router.use('/login', login)
router.use('/authorize', authorize)
router.use('/',refreshCookies, index)
router.use('/approvescantime',refreshCookies, approvescantime)
router.use('/approve',refreshCookies, approve)
router.use('/calendar',refreshCookies, calendar)
router.use('/contact',refreshCookies, contact)
router.use('/cross',refreshCookies, cross)
router.use('/delreq',refreshCookies, delreq)
router.use('/departmentleaveview',refreshCookies, departmentleaveview)
router.use('/easypass',refreshCookies, easypass)
router.use('/editentitle',refreshCookies, editentitle)
router.use('/exportmanager',refreshCookies, exportmanager)
router.use('/excelexport',refreshCookies, excelexport)
router.use('/forms',refreshCookies,forms)
router.use('/getip',refreshCookies, getip)
router.use('/getlar',refreshCookies, getlar)
router.use('/handbook',refreshCookies, handbook)
router.use('/hr',refreshCookies, hr)
router.use('/hrexport',refreshCookies, hrexport)
router.use('/lar',refreshCookies, lar)
router.use('/leavelist',refreshCookies, leavelist)
router.use('/leavereport',refreshCookies, leavereport)
router.use('/listtable',refreshCookies, listtable)
router.use('/memo',refreshCookies, memo)
router.use('/managerleavelist',refreshCookies, managerleavelist)
router.use('/manualattendance',refreshCookies,manualattendance)
router.use('/proc',refreshCookies, proc)
router.use('/profile',refreshCookies, profile)
router.use('/privacy',refreshCookies, privacy)
router.use('/refreshdata',refreshCookies, refreshdata)
router.use('/reporttime',refreshCookies, reporttime)
router.use('/reserve',refreshCookies, reserve)
router.use('/reservelist',refreshCookies,reservelist)
router.use('/saleactive',refreshCookies, saleactive)
router.use('/search',refreshCookies, search)
router.use('/searchb',refreshCookies, searchb)
router.use('/setting',refreshCookies, setting)
router.use('/setting2',refreshCookies, setting)
router.use('/sumlar',refreshCookies, sumlar)
router.use('/vacationa',refreshCookies, vacationa)

module.exports = router;